name: create_account
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Almarai
      fonts: 
        - asset: assets/fonts/AlmaraiExtraBold.ttf
          weight: 800
        - asset: assets/fonts/AlmaraiBold.ttf
          weight: 700
        - asset: assets/fonts/AlmaraiRegular.ttf
          weight: 400
